[phases.setup]
aptPkgs = ["ffmpeg"]

[phases.build]
cmds = [
  "pip install --no-cache-dir --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python downloader_bot.py"
